from __future__ import annotations

from langchain_core.prompts import ChatPromptTemplate

from app.orchestration.agents.course_resources.animation import (
    _animation_input,
    _deterministic_animation_html,
    _normalize_animation_html,
    _normalized_animation_quality_issue,
    run_section_html_animation_agent,
)
from app.orchestration.agents.course_resources.bilibili import (
    _search_bilibili_video_results,
    _verify_bilibili_video_metadata,
)
from app.orchestration.agents.course_resources.common import (
    _ANIMATION_TIMEOUT_SECONDS,
    _MARKDOWN_TIMEOUT_SECONDS,
    _RESOURCE_TIMEOUT_SECONDS,
    _VIDEO_SECTION_TIMEOUT_SECONDS,
    _VIDEO_TIMEOUT_SECONDS,
    _compose_section_content,
    _extract_brief_ids_from_markdown,
    _extract_recommendation_reason,
    _generated_markdown_seed_data,
    _invoke_resource_chain,
    _markdown_input,
    _merge_course_resource_data,
    _normalize_markdown_animation_briefs,
    _normalize_markdown_heading_variants,
    _normalize_markdown_step_blocks,
    _normalize_markdown_video_briefs,
    _persist_outline,
    _profile_summary_for_prompt,
    _run_with_retries,
    _section_by_id,
    _target_sections_for_scope,
    get_engine,
)
from app.orchestration.agents.course_resources.main import (
    create_section_html_animation_agent_node,
    create_section_markdown_agent_node,
    create_section_video_search_agent_node,
    stream_chapter_resource_generation,
)
from app.orchestration.agents.course_resources.markdown import (
    _markdown_quality_issue,
    _normalize_markdown_resources,
    _profile_learning_context_text,
    _section_body_from_expansion_text,
    run_section_markdown_agent,
)
from app.orchestration.agents.course_resources.video import (
    _fallback_cover_data_url,
    _find_verified_video_from_search,
    _normalized_video_quality_issue,
    _normalized_video_quality_issue_async,
    _search_youtube_video_results,
    _video_input,
    _video_search_queries,
    _video_specific_brief_terms,
    run_section_video_search_agent,
)

__all__ = [
    "ChatPromptTemplate",
    "run_section_markdown_agent",
    "run_section_html_animation_agent",
    "run_section_video_search_agent",
    "create_section_markdown_agent_node",
    "create_section_html_animation_agent_node",
    "create_section_video_search_agent_node",
    "stream_chapter_resource_generation",
    # Internals/Constants imported by test suites
    "_RESOURCE_TIMEOUT_SECONDS",
    "_MARKDOWN_TIMEOUT_SECONDS",
    "_VIDEO_TIMEOUT_SECONDS",
    "_VIDEO_SECTION_TIMEOUT_SECONDS",
    "_ANIMATION_TIMEOUT_SECONDS",
    "_invoke_resource_chain",
    "_markdown_input",
    "_section_by_id",
    "_target_sections_for_scope",
    "_merge_course_resource_data",
    "_compose_section_content",
    "_markdown_quality_issue",
    "_section_body_from_expansion_text",
    "_profile_learning_context_text",
    "_fallback_cover_data_url",
    "_find_verified_video_from_search",
    "_normalized_video_quality_issue",
    "_normalized_video_quality_issue_async",
    "_video_input",
    "_video_search_queries",
    "_animation_input",
    "_normalized_animation_quality_issue",
    "_extract_brief_ids_from_markdown",
    "_normalize_animation_html",
    "_normalize_markdown_resources",
    "_run_with_retries",
    "_video_specific_brief_terms",
    "_deterministic_animation_html",
    "_verify_bilibili_video_metadata",
    "_search_bilibili_video_results",
    "_search_youtube_video_results",
    "_normalize_markdown_heading_variants",
    "_normalize_markdown_step_blocks",
    "_normalize_markdown_video_briefs",
    "_normalize_markdown_animation_briefs",
    "_generated_markdown_seed_data",
    "_profile_summary_for_prompt",
    "_extract_recommendation_reason",
    "_persist_outline",
    "get_engine",
]
