/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	"/api/auth/register": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Register */
		post: operations["register_api_auth_register_post"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/auth/login": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Login */
		post: operations["login_api_auth_login_post"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/auth/oauth/mock": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Oauth */
		post: operations["oauth_api_auth_oauth_mock_post"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/auth/me": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Me */
		get: operations["me_api_auth_me_get"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/admin/accounts": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Accounts */
		get: operations["accounts_api_admin_accounts_get"];
		put?: never;
		/** Create */
		post: operations["create_api_admin_accounts_post"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/admin/accounts/batch": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Batch */
		post: operations["batch_api_admin_accounts_batch_post"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/admin/accounts/import": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Import Csv */
		post: operations["import_csv_api_admin_accounts_import_post"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/admin/accounts/export": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Export Csv */
		get: operations["export_csv_api_admin_accounts_export_get"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/admin/accounts/{uid}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		/** Update */
		put: operations["update_api_admin_accounts__uid__put"];
		post?: never;
		/** Delete */
		delete: operations["delete_api_admin_accounts__uid__delete"];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/admin/data/overview": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Overview */
		get: operations["overview_api_admin_data_overview_get"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/admin/data/cohorts": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Cohorts */
		get: operations["cohorts_api_admin_data_cohorts_get"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/admin/data/programs": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Programs */
		get: operations["programs_api_admin_data_programs_get"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/admin/data/users/{uid}/learning-data": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** User Learning Data */
		get: operations["user_learning_data_api_admin_data_users__uid__learning_data_get"];
		put?: never;
		post?: never;
		/** Delete User Learning Data */
		delete: operations["delete_user_learning_data_api_admin_data_users__uid__learning_data_delete"];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/admin/data/cohorts/{school}/{major}/{class_name}/program": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		/** Delete Cohort Program */
		delete: operations["delete_cohort_program_api_admin_data_cohorts__school___major___class_name__program_delete"];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/teacher/program": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Read Program */
		get: operations["read_program_api_teacher_program_get"];
		/** Save Program */
		put: operations["save_program_api_teacher_program_put"];
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/teacher/program/publish": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Publish Program */
		post: operations["publish_program_api_teacher_program_publish_post"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/student/matched-program": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Matched Program */
		get: operations["matched_program_api_student_matched_program_get"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/chat/start": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Start Chat
		 * @description Start a new chat session.
		 */
		post: operations["start_chat_api_chat_start_post"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/chat/message": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Send Message
		 * @description Send a message and receive SSE-streamed agent responses.
		 */
		post: operations["send_message_api_chat_message_post"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/chat/sessions/{session_id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get Session State
		 * @description Get the current state of a chat session.
		 */
		get: operations["get_session_state_api_chat_sessions__session_id__get"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/profile/dashboard": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get Dashboard */
		get: operations["get_dashboard_api_profile_dashboard_get"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/learning-path/me": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Read My Learning Path */
		get: operations["read_my_learning_path_api_learning_path_me_get"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/branch/canopy": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Read Canopy Overview */
		get: operations["read_canopy_overview_api_branch_canopy_get"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/branch/overview": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Read Branch Overview */
		get: operations["read_branch_overview_api_branch_overview_get"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/leaf/courses/{course_node_id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get Leaf Course */
		get: operations["get_leaf_course_api_leaf_courses__course_node_id__get"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/forest/courses/{course_node_id}/chapters/{chapter_id}/quiz": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get Forest Quiz Session */
		get: operations["get_forest_quiz_session_api_forest_courses__course_node_id__chapters__chapter_id__quiz_get"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/forest/courses/{course_node_id}/chapters/{chapter_id}/quiz/generate": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Generate Forest Quiz */
		post: operations["generate_forest_quiz_api_forest_courses__course_node_id__chapters__chapter_id__quiz_generate_post"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/forest/quizzes/{quiz_id}/attempts": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Create Forest Quiz Attempt */
		post: operations["create_forest_quiz_attempt_api_forest_quizzes__quiz_id__attempts_post"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/forest/quizzes/{quiz_id}/attempts/stream": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Submit Quiz Attempt Stream */
		post: operations["submit_quiz_attempt_stream_api_forest_quizzes__quiz_id__attempts_stream_post"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/forest/ai/stream": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Stream Forest Ai */
		post: operations["stream_forest_ai_api_forest_ai_stream_post"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/admin/knowledge-base/sources": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Admin Sources */
		get: operations["admin_sources_api_admin_knowledge_base_sources_get"];
		put?: never;
		/** Create Admin Source */
		post: operations["create_admin_source_api_admin_knowledge_base_sources_post"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/admin/knowledge-base/textbooks": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Admin Textbooks */
		get: operations["admin_textbooks_api_admin_knowledge_base_textbooks_get"];
		put?: never;
		/** Create Admin Textbook */
		post: operations["create_admin_textbook_api_admin_knowledge_base_textbooks_post"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/admin/knowledge-base/textbooks/{textbook_id}/publish": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Publish Admin Textbook */
		post: operations["publish_admin_textbook_api_admin_knowledge_base_textbooks__textbook_id__publish_post"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/admin/knowledge-base/textbooks/{textbook_id}/outline": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		/** Update Admin Textbook Outline */
		put: operations["update_admin_textbook_outline_api_admin_knowledge_base_textbooks__textbook_id__outline_put"];
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/admin/knowledge-base/textbooks/{textbook_id}/unpublish": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Unpublish Admin Textbook */
		post: operations["unpublish_admin_textbook_api_admin_knowledge_base_textbooks__textbook_id__unpublish_post"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/admin/knowledge-base/textbooks/{textbook_id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		/** Delete Admin Textbook */
		delete: operations["delete_admin_textbook_api_admin_knowledge_base_textbooks__textbook_id__delete"];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/admin/knowledge-base/textbooks/{textbook_id}/agent-organize": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Organize Admin Textbook */
		post: operations["organize_admin_textbook_api_admin_knowledge_base_textbooks__textbook_id__agent_organize_post"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/admin/knowledge-base/ingestion-jobs/{job_id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Read Admin Ingestion Job */
		get: operations["read_admin_ingestion_job_api_admin_knowledge_base_ingestion_jobs__job_id__get"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/admin/knowledge-base/agent": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Admin Knowledge Base Agent */
		post: operations["admin_knowledge_base_agent_api_admin_knowledge_base_agent_post"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/admin/knowledge-base/source-results/confirm": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Confirm Admin Source Result */
		post: operations["confirm_admin_source_result_api_admin_knowledge_base_source_results_confirm_post"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/admin/knowledge-base/uploads": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Upload Admin Textbook File */
		post: operations["upload_admin_textbook_file_api_admin_knowledge_base_uploads_post"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/admin/knowledge-base/gaps": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Admin Gaps */
		get: operations["admin_gaps_api_admin_knowledge_base_gaps_get"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/admin/knowledge-base/gaps/{gap_id}/find-materials": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Find Admin Gap Materials */
		post: operations["find_admin_gap_materials_api_admin_knowledge_base_gaps__gap_id__find_materials_post"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/admin/knowledge-base/gaps/{gap_id}/upload": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Upload Admin Gap Materials */
		post: operations["upload_admin_gap_materials_api_admin_knowledge_base_gaps__gap_id__upload_post"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/admin/knowledge-base/textbooks/{textbook_id}/extension-resources": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Admin Extension Resources */
		get: operations["admin_extension_resources_api_admin_knowledge_base_textbooks__textbook_id__extension_resources_get"];
		put?: never;
		/** Create Admin Extension Resource */
		post: operations["create_admin_extension_resource_api_admin_knowledge_base_textbooks__textbook_id__extension_resources_post"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/knowledge-base/gaps/{gap_id}/follow": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Follow Gap */
		post: operations["follow_gap_api_knowledge_base_gaps__gap_id__follow_post"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/knowledge-base/notices": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Notices */
		get: operations["notices_api_knowledge_base_notices_get"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/knowledge-base/notices/{notice_id}/read": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Read Notice */
		post: operations["read_notice_api_knowledge_base_notices__notice_id__read_post"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/health": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Health */
		get: operations["health_api_health_get"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		/** AdminAccountBatchRequest */
		AdminAccountBatchRequest: {
			/**
			 * Action
			 * @enum {string}
			 */
			action: "activate" | "deactivate" | "delete" | "set_role";
			/** Uids */
			uids: string[];
			/** Role */
			role?: ("student" | "admin") | null;
		};
		/** AdminAccountCreateRequest */
		AdminAccountCreateRequest: {
			/** Username */
			username: string;
			/** Identifier */
			identifier: string;
			/** Password */
			password: string;
			/**
			 * Role
			 * @enum {string}
			 */
			role: "student" | "admin";
			/**
			 * Is Active
			 * @default true
			 */
			is_active: boolean;
			/** School */
			school: string;
			/** Major */
			major: string;
			/** Class Name */
			class_name: string;
		};
		/** AdminAccountImportFailure */
		AdminAccountImportFailure: {
			/** Row */
			row: number;
			/** Identifier */
			identifier?: string | null;
			/** Reason */
			reason: string;
		};
		/** AdminAccountImportRequest */
		AdminAccountImportRequest: {
			/** Csv Text */
			csv_text: string;
		};
		/** AdminAccountImportResponse */
		AdminAccountImportResponse: {
			/** Created */
			created: number;
			/** Updated */
			updated: number;
			/** Failed */
			failed: number;
			/** Failures */
			failures?: components["schemas"]["AdminAccountImportFailure"][];
		};
		/** AdminAccountUpdateRequest */
		AdminAccountUpdateRequest: {
			/** Username */
			username: string;
			/** Identifier */
			identifier: string;
			/**
			 * Role
			 * @enum {string}
			 */
			role: "student" | "admin";
			/** Is Active */
			is_active: boolean;
			/** Password */
			password?: string | null;
			/** School */
			school: string;
			/** Major */
			major: string;
			/** Class Name */
			class_name: string;
		};
		/** AuthResponse */
		AuthResponse: {
			/** Access Token */
			access_token: string;
			/**
			 * Token Type
			 * @default bearer
			 */
			token_type: string;
			/**
			 * Auth Type
			 * @enum {string}
			 */
			auth_type: "password" | "oauth";
			user: components["schemas"]["UserRead"];
		};
		/** Body_upload_admin_textbook_file_api_admin_knowledge_base_uploads_post */
		Body_upload_admin_textbook_file_api_admin_knowledge_base_uploads_post: {
			/** Title */
			title: string;
			/**
			 * Language
			 * @default zh
			 */
			language: string;
			/**
			 * Description
			 * @default
			 */
			description: string;
			/**
			 * Tags
			 * @default
			 */
			tags: string;
			/** File */
			file: string;
		};
		/** BranchCourseNodeRead */
		BranchCourseNodeRead: {
			/** Course Node Id */
			course_node_id: string;
			/** Course Or Chapter Theme */
			course_or_chapter_theme: string;
			/** Course Goal */
			course_goal: string;
			/**
			 * Status
			 * @enum {string}
			 */
			status: "completed" | "current" | "locked";
			/** Has Outline */
			has_outline: boolean;
		};
		/** BranchOverviewReadResponse */
		BranchOverviewReadResponse: {
			/** Years */
			years: {
				[key: string]: components["schemas"]["BranchYearRead"];
			};
			/** Updated At */
			updated_at?: string | null;
		};
		/** BranchYearRead */
		BranchYearRead: {
			/** Grade Id */
			grade_id: string;
			/** Grade Name */
			grade_name: string;
			/** Has Courses */
			has_courses: boolean;
			/** Has Outline Content */
			has_outline_content: boolean;
			/** Is Clickable */
			is_clickable: boolean;
			/** Current Course Id */
			current_course_id?: string | null;
			/** Courses */
			courses: components["schemas"]["BranchCourseNodeRead"][];
		};
		/** CanopyCourseNode */
		CanopyCourseNode: {
			/** Id */
			id: string;
			/** Title */
			title: string;
			/** Grade */
			grade: string;
			/** Status */
			status: string;
			/** Score */
			score?: number | null;
			/** Description */
			description: string;
			/** Prerequisite Ids */
			prerequisite_ids?: string[];
		};
		/** CanopyMilestone */
		CanopyMilestone: {
			/** Date */
			date: string;
			/** Title */
			title: string;
			/** Desc */
			desc: string;
			/** Reached */
			reached: boolean;
		};
		/** CanopyOverviewResponse */
		CanopyOverviewResponse: {
			/** Courses */
			courses?: components["schemas"]["CanopyCourseNode"][];
			/** Growth Stage */
			growth_stage: number;
			/** Completed Count */
			completed_count: number;
			/** Active Rate */
			active_rate: number;
			/** Avg Score */
			avg_score: number;
			/** Focused Hours */
			focused_hours: number;
			/** Milestones */
			milestones?: components["schemas"]["CanopyMilestone"][];
			/** Quality Scores */
			quality_scores?: {
				[key: string]: components["schemas"]["CourseQualityScore"];
			};
		};
		/** ChatMessageRequest */
		ChatMessageRequest: {
			/** Session Id */
			session_id: string;
			/** Message */
			message: string;
			/**
			 * Image Attachment
			 * @description Base64 encoded image attachment
			 */
			image_attachment?: string | null;
		};
		/** ChatResponse */
		ChatResponse: {
			/** Session Id */
			session_id: string;
			/** Reply Text */
			reply_text?: string | null;
			/** Profile */
			profile?: {
				[key: string]: unknown;
			} | null;
			/** Year Learning Paths */
			year_learning_paths?: {
				[key: string]: unknown;
			} | null;
			/** Course Knowledge */
			course_knowledge?: {
				[key: string]: unknown;
			} | null;
		};
		/** ChatStartRequest */
		ChatStartRequest: {
			/** Query */
			query: string;
		};
		/** CourseQualityScore */
		CourseQualityScore: {
			/**
			 * Accuracy
			 * @default 0
			 */
			accuracy: number;
			/**
			 * Difficulty Fit
			 * @default 0
			 */
			difficulty_fit: number;
			/**
			 * Completeness
			 * @default 0
			 */
			completeness: number;
			/**
			 * Overall
			 * @default 0
			 */
			overall: number;
			/** Suggestions */
			suggestions?: string[];
			/** Scored At */
			scored_at?: string | null;
		};
		/** CultivationProgramRead */
		CultivationProgramRead: {
			/** Program Id */
			program_id: string;
			/** Teacher Uid */
			teacher_uid: string;
			/** Teacher Name */
			teacher_name: string;
			/** Teacher Identifier */
			teacher_identifier: string;
			/** School */
			school: string;
			/** Major */
			major: string;
			/** Class Name */
			class_name: string;
			/** Courses */
			courses?: {
				[key: string]: unknown;
			}[];
			/** Published At */
			published_at: string | null;
			/**
			 * Updated At
			 * Format: date-time
			 */
			updated_at: string;
		};
		/** CultivationProgramSaveRequest */
		CultivationProgramSaveRequest: {
			/** Courses */
			courses?: {
				[key: string]: unknown;
			}[];
			/** School */
			school?: string | null;
			/** Major */
			major?: string | null;
			/** Class Name */
			class_name?: string | null;
		};
		/** DataCohortRead */
		DataCohortRead: {
			/** School */
			school: string;
			/** Major */
			major: string;
			/** Class Name */
			class_name: string;
			/** Student Count */
			student_count: number;
			/** Admin Count */
			admin_count: number;
			/** Has Program */
			has_program: boolean;
			/** Program Teacher Name */
			program_teacher_name?: string | null;
			/** Program Updated At */
			program_updated_at?: string | null;
		};
		/** DataOverviewResponse */
		DataOverviewResponse: {
			/** Accounts */
			accounts: {
				[key: string]: number;
			};
			/** Cohorts */
			cohorts: number;
			/** Programs */
			programs: number;
			/** Learning Data */
			learning_data: {
				[key: string]: number;
			};
		};
		/** ForestAiContext */
		ForestAiContext: {
			/** Course Node Id */
			course_node_id: string;
			/** Chapter Id */
			chapter_id: string;
			/** Quiz Id */
			quiz_id?: string | null;
			/** Question Id */
			question_id?: string | null;
			/** Question */
			question?: {
				[key: string]: unknown;
			} | null;
			/** Answer */
			answer?: unknown | null;
			/** Grading Result */
			grading_result?: {
				[key: string]: unknown;
			} | null;
		};
		/** ForestAiStreamRequest */
		ForestAiStreamRequest: {
			/** Course Node Id */
			course_node_id: string;
			/** Chapter Id */
			chapter_id: string;
			/** Quiz Id */
			quiz_id?: string | null;
			/** Question Id */
			question_id?: string | null;
			/** Message */
			message: string;
			active_question_context: components["schemas"]["ForestAiContext"];
			/**
			 * Image Attachment
			 * @description Base64 encoded image attachment
			 */
			image_attachment?: string | null;
		};
		/** ForestAttemptRead */
		ForestAttemptRead: {
			/** Attempt Id */
			attempt_id: string;
			/** Quiz Id */
			quiz_id: string;
			/** Score */
			score: number;
			/** Passed */
			passed: boolean;
			/** Answers */
			answers: {
				[key: string]: unknown;
			};
			/** Grading Result */
			grading_result: {
				[key: string]: unknown;
			};
			/**
			 * Created At
			 * Format: date-time
			 */
			created_at: string;
		};
		/** ForestChapterProgressRead */
		ForestChapterProgressRead: {
			/** Course Node Id */
			course_node_id: string;
			/** Chapter Id */
			chapter_id: string;
			/**
			 * State
			 * @enum {string}
			 */
			state: "locked" | "available" | "passed";
			/** Best Score */
			best_score: number;
			/** Latest Attempt Id */
			latest_attempt_id?: string | null;
			/** Passed At */
			passed_at?: string | null;
			/**
			 * Updated At
			 * Format: date-time
			 */
			updated_at: string;
		};
		/** ForestQuizAttemptCreateRequest */
		ForestQuizAttemptCreateRequest: {
			/** Answers */
			answers: {
				[key: string]: unknown;
			};
		};
		/** ForestQuizGenerateRequest */
		ForestQuizGenerateRequest: {
			/**
			 * Regenerate
			 * @default false
			 */
			regenerate: boolean;
		};
		/** ForestQuizQuestionRead */
		ForestQuizQuestionRead: {
			/** Question Id */
			question_id: string;
			/**
			 * Type
			 * @enum {string}
			 */
			type: "single_choice" | "code" | "image_upload";
			/** Prompt */
			prompt: string;
			/** Options */
			options?: {
				[key: string]: unknown;
			}[];
			/**
			 * Starter Code
			 * @default
			 */
			starter_code: string;
			/**
			 * Image Prompt
			 * @default
			 */
			image_prompt: string;
			/**
			 * Points
			 * @default 0
			 */
			points: number;
		};
		/** ForestQuizRead */
		ForestQuizRead: {
			/** Quiz Id */
			quiz_id: string;
			/** Course Node Id */
			course_node_id: string;
			/** Chapter Id */
			chapter_id: string;
			/**
			 * Status
			 * @enum {string}
			 */
			status: "generating" | "ready" | "error";
			/** Questions */
			questions?: components["schemas"]["ForestQuizQuestionRead"][];
			/**
			 * Generation Error
			 * @default
			 */
			generation_error: string;
			/**
			 * Created At
			 * Format: date-time
			 */
			created_at: string;
			/**
			 * Updated At
			 * Format: date-time
			 */
			updated_at: string;
		};
		/** ForestQuizSessionReadResponse */
		ForestQuizSessionReadResponse: {
			course: components["schemas"]["LeafCourseRead"];
			/** Chapter */
			chapter: {
				[key: string]: unknown;
			};
			quiz?: components["schemas"]["ForestQuizRead"] | null;
			latest_attempt?: components["schemas"]["ForestAttemptRead"] | null;
			progress: components["schemas"]["ForestChapterProgressRead"];
			/** Next Unlocked Chapter Id */
			next_unlocked_chapter_id?: string | null;
			/** Next Course Id */
			next_course_id?: string | null;
		};
		/** HTTPValidationError */
		HTTPValidationError: {
			/** Detail */
			detail?: components["schemas"]["ValidationError"][];
		};
		/** HealthResponse */
		HealthResponse: {
			/**
			 * Status
			 * @constant
			 */
			status: "ok";
			/**
			 * Database
			 * @constant
			 */
			database: "connected";
		};
		/** KnowledgeBaseAgentGapHit */
		KnowledgeBaseAgentGapHit: {
			/** Gap Id */
			gap_id: string;
			/** Normalized Topic */
			normalized_topic: string;
			/**
			 * Status
			 * @enum {string}
			 */
			status:
				| "open"
				| "material_searching"
				| "material_found"
				| "resolved"
				| "closed";
			/**
			 * Reason
			 * @default
			 */
			reason: string;
		};
		/** KnowledgeBaseAgentRequest */
		KnowledgeBaseAgentRequest: {
			/** Message */
			message: string;
		};
		/** KnowledgeBaseAgentResponse */
		KnowledgeBaseAgentResponse: {
			/** Reply Text */
			reply_text: string;
			/** Selected Textbook Id */
			selected_textbook_id?: string | null;
			/** Selected Source Result Id */
			selected_source_result_id?: string | null;
			/** Textbook Hits */
			textbook_hits?: components["schemas"]["KnowledgeBaseAgentTextbookHit"][];
			/** Gap Hits */
			gap_hits?: components["schemas"]["KnowledgeBaseAgentGapHit"][];
			/** Source Results */
			source_results?: components["schemas"]["KnowledgeBaseSourceResult"][];
		};
		/** KnowledgeBaseAgentTextbookHit */
		KnowledgeBaseAgentTextbookHit: {
			/** Textbook Id */
			textbook_id: string;
			/** Title */
			title: string;
			/** Source Name */
			source_name: string;
			/**
			 * Student Availability Status
			 * @enum {string}
			 */
			student_availability_status:
				| "draft"
				| "published"
				| "unpublished"
				| "archived";
			/** Score */
			score: number;
			/**
			 * Reason
			 * @default
			 */
			reason: string;
		};
		/** KnowledgeBaseIngestionJobRead */
		KnowledgeBaseIngestionJobRead: {
			/** Job Id */
			job_id: string;
			/** Textbook Id */
			textbook_id: string;
			/** Job Type */
			job_type: string;
			/**
			 * Status
			 * @enum {string}
			 */
			status: "queued" | "running" | "failed" | "completed";
			/** Error Message */
			error_message: string;
			/**
			 * Created At
			 * Format: date-time
			 */
			created_at: string;
			/** Started At */
			started_at: string | null;
			/** Finished At */
			finished_at: string | null;
		};
		/** KnowledgeBaseSourceConfirmRequest */
		KnowledgeBaseSourceConfirmRequest: {
			source_result: components["schemas"]["KnowledgeBaseSourceResult"];
		};
		/** KnowledgeBaseSourceConfirmResponse */
		KnowledgeBaseSourceConfirmResponse: {
			textbook: components["schemas"]["TextbookRead"];
			job: components["schemas"]["KnowledgeBaseIngestionJobRead"];
		};
		/** KnowledgeBaseSourceResult */
		KnowledgeBaseSourceResult: {
			/** Source Result Id */
			source_result_id: string;
			/** Title */
			title: string;
			/**
			 * Original Title
			 * @default
			 */
			original_title: string;
			/**
			 * Language
			 * @default
			 */
			language: string;
			/** Source Url */
			source_url: string;
			/**
			 * Source Type
			 * @enum {string}
			 */
			source_type: "pdf" | "html";
			/**
			 * Provider Name
			 * @default
			 */
			provider_name: string;
			/**
			 * Description
			 * @default
			 */
			description: string;
			/** Tags */
			tags?: string[];
			/** Parseability Score */
			parseability_score: number;
			/**
			 * Parseability Reason
			 * @default
			 */
			parseability_reason: string;
			/**
			 * Topic Summary
			 * @default
			 */
			topic_summary: string;
			/**
			 * Is Recommended
			 * @default false
			 */
			is_recommended: boolean;
		};
		/** KnowledgeGapAdminRead */
		KnowledgeGapAdminRead: {
			/** Gap Id */
			gap_id: string;
			/** Normalized Topic */
			normalized_topic: string;
			/** Trigger Count */
			trigger_count: number;
			/** Follow Count */
			follow_count: number;
			/** Latest Triggered At */
			latest_triggered_at: string | null;
			/** Student Goal Summaries */
			student_goal_summaries: string[];
			/**
			 * Status
			 * @enum {string}
			 */
			status:
				| "open"
				| "material_searching"
				| "material_found"
				| "resolved"
				| "closed";
			/** Resolved Textbook Id */
			resolved_textbook_id: string | null;
			/** Resolved At */
			resolved_at: string | null;
			/** Sources */
			sources?: components["schemas"]["KnowledgeSourceRead"][];
			/** Actions */
			actions?: string[];
		};
		/** KnowledgeGapFindMaterialsResponse */
		KnowledgeGapFindMaterialsResponse: {
			gap: components["schemas"]["KnowledgeGapRead"];
			/** Sources */
			sources: components["schemas"]["KnowledgeSourceRead"][];
		};
		/** KnowledgeGapFollowRead */
		KnowledgeGapFollowRead: {
			/** Follow Id */
			follow_id: string;
			/** Gap Id */
			gap_id: string;
			/** User Uid */
			user_uid: string;
			/**
			 * Created At
			 * Format: date-time
			 */
			created_at: string;
		};
		/** KnowledgeGapNoticeActionPayload */
		KnowledgeGapNoticeActionPayload: {
			/**
			 * Action
			 * @constant
			 */
			action: "regenerate_learning_path_intake";
			/** Learning Topic */
			learning_topic: string;
			/** Textbook Id */
			textbook_id: string;
		};
		/** KnowledgeGapNoticeRead */
		KnowledgeGapNoticeRead: {
			/** Notice Id */
			notice_id: string;
			/** Gap Id */
			gap_id: string;
			/** User Uid */
			user_uid: string;
			/**
			 * Notice Type
			 * @constant
			 */
			notice_type: "knowledge_gap_resolved";
			/** Title */
			title: string;
			/** Body */
			body: string;
			/** Action Label */
			action_label: string;
			action_payload: components["schemas"]["KnowledgeGapNoticeActionPayload"];
			/** Read At */
			read_at: string | null;
			/**
			 * Created At
			 * Format: date-time
			 */
			created_at: string;
		};
		/** KnowledgeGapRead */
		KnowledgeGapRead: {
			/** Gap Id */
			gap_id: string;
			/** Normalized Topic */
			normalized_topic: string;
			/** Trigger Count */
			trigger_count: number;
			/** Follow Count */
			follow_count: number;
			/** Latest Triggered At */
			latest_triggered_at: string | null;
			/** Student Goal Summaries */
			student_goal_summaries: string[];
			/**
			 * Status
			 * @enum {string}
			 */
			status:
				| "open"
				| "material_searching"
				| "material_found"
				| "resolved"
				| "closed";
			/** Resolved Textbook Id */
			resolved_textbook_id: string | null;
			/** Resolved At */
			resolved_at: string | null;
		};
		/** KnowledgeGapUploadResponse */
		KnowledgeGapUploadResponse: {
			gap: components["schemas"]["KnowledgeGapRead"];
			textbook: components["schemas"]["TextbookRead"];
		};
		/** KnowledgeSourceCreateRequest */
		KnowledgeSourceCreateRequest: {
			/** Source Id */
			source_id: string;
			/** Name */
			name: string;
			/**
			 * Base Url
			 * @default
			 */
			base_url: string;
			/**
			 * Status
			 * @default enabled
			 * @enum {string}
			 */
			status: "enabled" | "disabled";
			/**
			 * Source Kind
			 * @default
			 */
			source_kind: string;
			/**
			 * Download Requirement
			 * @default
			 */
			download_requirement: string;
			/**
			 * Ai Search Requirement
			 * @default
			 */
			ai_search_requirement: string;
			/**
			 * Download Status
			 * @default unverified
			 * @enum {string}
			 */
			download_status: "unverified" | "verified" | "failed";
			/**
			 * Parse Status
			 * @default unverified
			 * @enum {string}
			 */
			parse_status: "unverified" | "supported" | "failed";
			/**
			 * License Review Status
			 * @default unreviewed
			 * @enum {string}
			 */
			license_review_status: "unreviewed" | "approved" | "rejected";
			/**
			 * Human Review Status
			 * @default unreviewed
			 * @enum {string}
			 */
			human_review_status: "unreviewed" | "reviewed";
		};
		/** KnowledgeSourceRead */
		KnowledgeSourceRead: {
			/** Source Id */
			source_id: string;
			/** Name */
			name: string;
			/**
			 * Base Url
			 * @default
			 */
			base_url: string;
			/**
			 * Status
			 * @default enabled
			 * @enum {string}
			 */
			status: "enabled" | "disabled";
			/**
			 * Source Kind
			 * @default
			 */
			source_kind: string;
			/**
			 * Download Requirement
			 * @default
			 */
			download_requirement: string;
			/**
			 * Ai Search Requirement
			 * @default
			 */
			ai_search_requirement: string;
			/**
			 * Download Status
			 * @default unverified
			 * @enum {string}
			 */
			download_status: "unverified" | "verified" | "failed";
			/**
			 * Parse Status
			 * @default unverified
			 * @enum {string}
			 */
			parse_status: "unverified" | "supported" | "failed";
			/**
			 * License Review Status
			 * @default unreviewed
			 * @enum {string}
			 */
			license_review_status: "unreviewed" | "approved" | "rejected";
			/**
			 * Human Review Status
			 * @default unreviewed
			 * @enum {string}
			 */
			human_review_status: "unreviewed" | "reviewed";
		};
		/** LeafCourseRead */
		LeafCourseRead: {
			/** Course Node Id */
			course_node_id: string;
			/** Grade Id */
			grade_id: string;
			/** Course Or Chapter Theme */
			course_or_chapter_theme: string;
			/** Course Goal */
			course_goal: string;
			/**
			 * Status
			 * @enum {string}
			 */
			status: "completed" | "current" | "locked";
			/** Has Outline */
			has_outline: boolean;
		};
		/** LeafCourseReadResponse */
		LeafCourseReadResponse: {
			/**
			 * Access State
			 * @enum {string}
			 */
			access_state: "available" | "locked";
			course: components["schemas"]["LeafCourseRead"];
			/** Outline */
			outline?: {
				[key: string]: unknown;
			} | null;
			/** Sections */
			sections?: {
				[key: string]: unknown;
			}[];
			/** Section Composed Markdowns */
			section_composed_markdowns?: {
				[key: string]: {
					[key: string]: unknown;
				};
			};
			/** Section Resource Errors */
			section_resource_errors?: {
				[key: string]: {
					[key: string]: unknown;
				};
			};
			generation_status?:
				| components["schemas"]["LeafGenerationStatusRead"]
				| null;
			/** Can Generate */
			can_generate: boolean;
			/** First Generatable Chapter Id */
			first_generatable_chapter_id?: string | null;
			/** Locked Reason */
			locked_reason?: string | null;
		};
		/** LeafGenerationStatusRead */
		LeafGenerationStatusRead: {
			/** Course Node Id */
			course_node_id: string;
			/** Chapter Section Id */
			chapter_section_id: string;
			/**
			 * Status
			 * @constant
			 */
			status: "running";
			/** Message */
			message: string;
		};
		/** LoginRequest */
		LoginRequest: {
			/** Account */
			account: string;
			/** Password */
			password: string;
		};
		/** OAuthRequest */
		OAuthRequest: {
			/**
			 * Provider
			 * @enum {string}
			 */
			provider: "qq" | "xuexitong";
			/** Authorization Code */
			authorization_code: string;
		};
		/** RegisterRequest */
		RegisterRequest: {
			/** Username */
			username: string;
			/** Identifier */
			identifier: string;
			/** Password */
			password: string;
			/** Confirm Password */
			confirm_password: string;
			/**
			 * Role
			 * @default student
			 * @enum {string}
			 */
			role: "student" | "admin";
			/** School */
			school: string;
			/** Major */
			major: string;
			/** Class Name */
			class_name: string;
		};
		/** SessionStateResponse */
		SessionStateResponse: {
			/** Session Id */
			session_id: string;
			/** User Uid */
			user_uid: string;
			/** Messages */
			messages?: {
				[key: string]: unknown;
			}[];
			/** Profile */
			profile?: {
				[key: string]: unknown;
			} | null;
			/** Year Learning Paths */
			year_learning_paths?: {
				[key: string]: unknown;
			} | null;
			/** Latest Grade Year */
			latest_grade_year?: string | null;
			/** Course Knowledge */
			course_knowledge?: {
				[key: string]: unknown;
			} | null;
			/**
			 * Updated At
			 * Format: date-time
			 */
			updated_at: string;
		};
		/** StructuredTextbookCreateRequest */
		StructuredTextbookCreateRequest: {
			textbook: components["schemas"]["TextbookCreateRequest"];
			/** Sections */
			sections: components["schemas"]["TextbookSectionContentCreateRequest"][];
		};
		/** TextbookCreateRequest */
		TextbookCreateRequest: {
			/** Textbook Id */
			textbook_id: string;
			/** Source Id */
			source_id: string;
			/** Title */
			title: string;
			/**
			 * Original Title
			 * @default
			 */
			original_title: string;
			/**
			 * Language
			 * @default
			 */
			language: string;
			/**
			 * Translated Language
			 * @default
			 */
			translated_language: string;
			/**
			 * Description
			 * @default
			 */
			description: string;
			/** Tags */
			tags?: string[];
			/**
			 * Download Url
			 * @default
			 */
			download_url: string;
			/**
			 * File Asset Url
			 * @default
			 */
			file_asset_url: string;
			/** Outline */
			outline?: {
				[key: string]: unknown;
			};
			/**
			 * Ingestion Status
			 * @default not_started
			 * @enum {string}
			 */
			ingestion_status:
				| "not_started"
				| "processing"
				| "failed"
				| "ready_for_outline_review"
				| "completed";
			/**
			 * Outline Review Status
			 * @default unreviewed
			 * @enum {string}
			 */
			outline_review_status: "unreviewed" | "approved";
			/**
			 * Student Availability Status
			 * @default draft
			 * @enum {string}
			 */
			student_availability_status:
				| "draft"
				| "published"
				| "unpublished"
				| "archived";
			/**
			 * Ingestion Error Message
			 * @default
			 */
			ingestion_error_message: string;
		};
		/** TextbookExtensionResourceCreateRequest */
		TextbookExtensionResourceCreateRequest: {
			/** Resource Id */
			resource_id: string;
			/** Section Id */
			section_id: string;
			/**
			 * Resource Type
			 * @default
			 */
			resource_type: string;
			/** Title Zh */
			title_zh: string;
			/**
			 * Description Zh
			 * @default
			 */
			description_zh: string;
			/**
			 * Render Mode
			 * @default reader
			 * @enum {string}
			 */
			render_mode: "reader" | "video" | "webpage";
			/**
			 * Url
			 * @default
			 */
			url: string;
			/**
			 * Cover Url
			 * @default
			 */
			cover_url: string;
			/**
			 * Source Name
			 * @default
			 */
			source_name: string;
			/**
			 * Status
			 * @default
			 */
			status: string;
		};
		/** TextbookExtensionResourceRead */
		TextbookExtensionResourceRead: {
			/** Resource Id */
			resource_id: string;
			/** Section Id */
			section_id: string;
			/**
			 * Resource Type
			 * @default
			 */
			resource_type: string;
			/** Title Zh */
			title_zh: string;
			/**
			 * Description Zh
			 * @default
			 */
			description_zh: string;
			/**
			 * Render Mode
			 * @default reader
			 * @enum {string}
			 */
			render_mode: "reader" | "video" | "webpage";
			/**
			 * Url
			 * @default
			 */
			url: string;
			/**
			 * Cover Url
			 * @default
			 */
			cover_url: string;
			/**
			 * Source Name
			 * @default
			 */
			source_name: string;
			/**
			 * Status
			 * @default
			 */
			status: string;
			/** Textbook Id */
			textbook_id: string;
		};
		/** TextbookRead */
		TextbookRead: {
			/** Textbook Id */
			textbook_id: string;
			/** Source Id */
			source_id: string;
			/** Title */
			title: string;
			/**
			 * Original Title
			 * @default
			 */
			original_title: string;
			/**
			 * Language
			 * @default
			 */
			language: string;
			/**
			 * Translated Language
			 * @default
			 */
			translated_language: string;
			/**
			 * Description
			 * @default
			 */
			description: string;
			/** Tags */
			tags?: string[];
			/**
			 * Download Url
			 * @default
			 */
			download_url: string;
			/**
			 * File Asset Url
			 * @default
			 */
			file_asset_url: string;
			/** Outline */
			outline?: {
				[key: string]: unknown;
			};
			/**
			 * Ingestion Status
			 * @default not_started
			 * @enum {string}
			 */
			ingestion_status:
				| "not_started"
				| "processing"
				| "failed"
				| "ready_for_outline_review"
				| "completed";
			/**
			 * Outline Review Status
			 * @default unreviewed
			 * @enum {string}
			 */
			outline_review_status: "unreviewed" | "approved";
			/**
			 * Student Availability Status
			 * @default draft
			 * @enum {string}
			 */
			student_availability_status:
				| "draft"
				| "published"
				| "unpublished"
				| "archived";
			/**
			 * Ingestion Error Message
			 * @default
			 */
			ingestion_error_message: string;
			/** Published At */
			published_at?: string | null;
			/** Unpublished At */
			unpublished_at?: string | null;
			/** Archived At */
			archived_at?: string | null;
		};
		/** TextbookSectionContentCreateRequest */
		TextbookSectionContentCreateRequest: {
			/** Section Content Id */
			section_content_id: string;
			/** Section Id */
			section_id: string;
			/** Parent Section Id */
			parent_section_id?: string | null;
			/**
			 * Order Index
			 * @default 0
			 */
			order_index: number;
			/** Title */
			title: string;
			/**
			 * Original Title
			 * @default
			 */
			original_title: string;
			/**
			 * Content Zh
			 * @default
			 */
			content_zh: string;
			/**
			 * Content Char Count
			 * @default 0
			 */
			content_char_count: number;
		};
		/** UserLearningDataRead */
		UserLearningDataRead: {
			user: components["schemas"]["UserRead"];
			/** Profile */
			profile?: {
				[key: string]: unknown;
			} | null;
			/** Year Learning Paths */
			year_learning_paths?: {
				[key: string]: unknown;
			}[];
			/** Course Outlines */
			course_outlines?: {
				[key: string]: unknown;
			}[];
			/** Chapter Quizzes */
			chapter_quizzes?: {
				[key: string]: unknown;
			}[];
			/** Chapter Progress */
			chapter_progress?: {
				[key: string]: unknown;
			}[];
			/** Chapter Weaknesses */
			chapter_weaknesses?: {
				[key: string]: unknown;
			}[];
			/** Resource Quality */
			resource_quality?: {
				[key: string]: unknown;
			}[];
			/** Conversation Sessions */
			conversation_sessions?: {
				[key: string]: unknown;
			}[];
		};
		/** UserRead */
		UserRead: {
			/** Uid */
			uid: string;
			/** Username */
			username: string;
			/** Identifier */
			identifier: string;
			/**
			 * Role
			 * @enum {string}
			 */
			role: "student" | "admin";
			/** School */
			school: string;
			/** Major */
			major: string;
			/** Class Name */
			class_name: string;
			/** Provider */
			provider: string;
			/** Is Active */
			is_active: boolean;
			/**
			 * Created At
			 * Format: date-time
			 */
			created_at: string;
			/** Last Login At */
			last_login_at: string | null;
		};
		/** ValidationError */
		ValidationError: {
			/** Location */
			loc: (string | number)[];
			/** Message */
			msg: string;
			/** Error Type */
			type: string;
			/** Input */
			input?: unknown;
			/** Context */
			ctx?: Record<string, never>;
		};
		/** YearLearningPathsReadResponse */
		YearLearningPathsReadResponse: {
			/** Year Learning Paths */
			year_learning_paths: {
				[key: string]: {
					[key: string]: unknown;
				};
			};
			/** Updated At */
			updated_at?: string | null;
		};
	};
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
	register_api_auth_register_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["RegisterRequest"];
			};
		};
		responses: {
			/** @description Successful Response */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["AuthResponse"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	login_api_auth_login_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["LoginRequest"];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["AuthResponse"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	oauth_api_auth_oauth_mock_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["OAuthRequest"];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["AuthResponse"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	me_api_auth_me_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["UserRead"];
				};
			};
		};
	};
	accounts_api_admin_accounts_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["UserRead"][];
				};
			};
		};
	};
	create_api_admin_accounts_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["AdminAccountCreateRequest"];
			};
		};
		responses: {
			/** @description Successful Response */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["UserRead"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	batch_api_admin_accounts_batch_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["AdminAccountBatchRequest"];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["UserRead"][];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	import_csv_api_admin_accounts_import_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["AdminAccountImportRequest"];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["AdminAccountImportResponse"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	export_csv_api_admin_accounts_export_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": unknown;
				};
			};
		};
	};
	update_api_admin_accounts__uid__put: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				uid: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["AdminAccountUpdateRequest"];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["UserRead"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	delete_api_admin_accounts__uid__delete: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				uid: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	overview_api_admin_data_overview_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["DataOverviewResponse"];
				};
			};
		};
	};
	cohorts_api_admin_data_cohorts_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["DataCohortRead"][];
				};
			};
		};
	};
	programs_api_admin_data_programs_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["CultivationProgramRead"][];
				};
			};
		};
	};
	user_learning_data_api_admin_data_users__uid__learning_data_get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				uid: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["UserLearningDataRead"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	delete_user_learning_data_api_admin_data_users__uid__learning_data_delete: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				uid: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	delete_cohort_program_api_admin_data_cohorts__school___major___class_name__program_delete: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				school: string;
				major: string;
				class_name: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	read_program_api_teacher_program_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json":
						| components["schemas"]["CultivationProgramRead"]
						| null;
				};
			};
		};
	};
	save_program_api_teacher_program_put: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["CultivationProgramSaveRequest"];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["CultivationProgramRead"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	publish_program_api_teacher_program_publish_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["CultivationProgramSaveRequest"];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["CultivationProgramRead"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	matched_program_api_student_matched_program_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json":
						| components["schemas"]["CultivationProgramRead"]
						| null;
				};
			};
		};
	};
	start_chat_api_chat_start_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["ChatStartRequest"];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ChatResponse"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	send_message_api_chat_message_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["ChatMessageRequest"];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": unknown;
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	get_session_state_api_chat_sessions__session_id__get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				session_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["SessionStateResponse"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	get_dashboard_api_profile_dashboard_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": {
						[key: string]: unknown;
					};
				};
			};
		};
	};
	read_my_learning_path_api_learning_path_me_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["YearLearningPathsReadResponse"];
				};
			};
		};
	};
	read_canopy_overview_api_branch_canopy_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["CanopyOverviewResponse"];
				};
			};
		};
	};
	read_branch_overview_api_branch_overview_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["BranchOverviewReadResponse"];
				};
			};
		};
	};
	get_leaf_course_api_leaf_courses__course_node_id__get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				course_node_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["LeafCourseReadResponse"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	get_forest_quiz_session_api_forest_courses__course_node_id__chapters__chapter_id__quiz_get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				course_node_id: string;
				chapter_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ForestQuizSessionReadResponse"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	generate_forest_quiz_api_forest_courses__course_node_id__chapters__chapter_id__quiz_generate_post: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				course_node_id: string;
				chapter_id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["ForestQuizGenerateRequest"];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ForestQuizRead"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	create_forest_quiz_attempt_api_forest_quizzes__quiz_id__attempts_post: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				quiz_id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["ForestQuizAttemptCreateRequest"];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ForestAttemptRead"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	submit_quiz_attempt_stream_api_forest_quizzes__quiz_id__attempts_stream_post: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				quiz_id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["ForestQuizAttemptCreateRequest"];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": unknown;
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	stream_forest_ai_api_forest_ai_stream_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["ForestAiStreamRequest"];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": unknown;
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	admin_sources_api_admin_knowledge_base_sources_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["KnowledgeSourceRead"][];
				};
			};
		};
	};
	create_admin_source_api_admin_knowledge_base_sources_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["KnowledgeSourceCreateRequest"];
			};
		};
		responses: {
			/** @description Successful Response */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["KnowledgeSourceRead"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	admin_textbooks_api_admin_knowledge_base_textbooks_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["TextbookRead"][];
				};
			};
		};
	};
	create_admin_textbook_api_admin_knowledge_base_textbooks_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["StructuredTextbookCreateRequest"];
			};
		};
		responses: {
			/** @description Successful Response */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["TextbookRead"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	publish_admin_textbook_api_admin_knowledge_base_textbooks__textbook_id__publish_post: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				textbook_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["TextbookRead"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	update_admin_textbook_outline_api_admin_knowledge_base_textbooks__textbook_id__outline_put: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				textbook_id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": {
					[key: string]: unknown;
				};
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["TextbookRead"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	unpublish_admin_textbook_api_admin_knowledge_base_textbooks__textbook_id__unpublish_post: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				textbook_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["TextbookRead"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	delete_admin_textbook_api_admin_knowledge_base_textbooks__textbook_id__delete: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				textbook_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	organize_admin_textbook_api_admin_knowledge_base_textbooks__textbook_id__agent_organize_post: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				textbook_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["KnowledgeBaseIngestionJobRead"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	read_admin_ingestion_job_api_admin_knowledge_base_ingestion_jobs__job_id__get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				job_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["KnowledgeBaseIngestionJobRead"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	admin_knowledge_base_agent_api_admin_knowledge_base_agent_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["KnowledgeBaseAgentRequest"];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["KnowledgeBaseAgentResponse"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	confirm_admin_source_result_api_admin_knowledge_base_source_results_confirm_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["KnowledgeBaseSourceConfirmRequest"];
			};
		};
		responses: {
			/** @description Successful Response */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["KnowledgeBaseSourceConfirmResponse"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	upload_admin_textbook_file_api_admin_knowledge_base_uploads_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"multipart/form-data": components["schemas"]["Body_upload_admin_textbook_file_api_admin_knowledge_base_uploads_post"];
			};
		};
		responses: {
			/** @description Successful Response */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["KnowledgeBaseSourceConfirmResponse"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	admin_gaps_api_admin_knowledge_base_gaps_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["KnowledgeGapAdminRead"][];
				};
			};
		};
	};
	find_admin_gap_materials_api_admin_knowledge_base_gaps__gap_id__find_materials_post: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				gap_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["KnowledgeGapFindMaterialsResponse"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	upload_admin_gap_materials_api_admin_knowledge_base_gaps__gap_id__upload_post: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				gap_id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["StructuredTextbookCreateRequest"];
			};
		};
		responses: {
			/** @description Successful Response */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["KnowledgeGapUploadResponse"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	admin_extension_resources_api_admin_knowledge_base_textbooks__textbook_id__extension_resources_get: {
		parameters: {
			query?: {
				section_id?: string[];
			};
			header?: never;
			path: {
				textbook_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["TextbookExtensionResourceRead"][];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	create_admin_extension_resource_api_admin_knowledge_base_textbooks__textbook_id__extension_resources_post: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				textbook_id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["TextbookExtensionResourceCreateRequest"];
			};
		};
		responses: {
			/** @description Successful Response */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["TextbookExtensionResourceRead"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	follow_gap_api_knowledge_base_gaps__gap_id__follow_post: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				gap_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["KnowledgeGapFollowRead"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	notices_api_knowledge_base_notices_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["KnowledgeGapNoticeRead"][];
				};
			};
		};
	};
	read_notice_api_knowledge_base_notices__notice_id__read_post: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				notice_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["KnowledgeGapNoticeRead"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	health_api_health_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HealthResponse"];
				};
			};
		};
	};
}
